### ISSUE TITLE
ImportError: cannot import name cython_nms

### ISSUE THREAD

**Issue by zhanghang1989** [longcw/faster_rcnn_pytorch#10]
I am trying the demo script, but got this error: `ImportError: cannot import name cython_nms` . Any suggestions? Thanks!

**Comment by longcw** [comment]
Did you run 
```
cd faster_rcnn_pytorch/faster_rcnn
./make.sh
```

**Comment by zhanghang1989** [comment]
Thanks for following up. Yes, I did. I haven't received any compiling error.

**Comment by lxtGH** [comment]
I run the ./make.sh, but still have this error

**Comment by yangshao** [comment]
@lxtGH me2, did you find the solution?

**Comment by chenggangdu** [comment]
how to run the above codes?
