### ISSUE TITLE
AssertionError: Single batch only

### ISSUE THREAD

**Issue by abhiML** [longcw/faster_rcnn_pytorch#16]
<bound method pascal_voc.default_roidb of <faster_rcnn.datasets.pascal_voc.pascal_voc object at 0x7fd20fbaf0d0>>
voc_2007_trainval gt roidb loaded from /home/ubuntu/faster_rcnn_pytorch/data/cache/voc_2007_trainval_gt_roidb.pkl
Traceback (most recent call last):
  File "train.py", line 115, in <module>
    blobs = data_layer.forward()
  File "/home/ubuntu/faster_rcnn_pytorch/faster_rcnn/roi_data_layer/layer.py", line 74, in forward
    blobs = self._get_next_minibatch()
  File "/home/ubuntu/faster_rcnn_pytorch/faster_rcnn/roi_data_layer/layer.py", line 70, in _get_next_minibatch
    return get_minibatch(minibatch_db, self._num_classes)
  File "/home/ubuntu/faster_rcnn_pytorch/faster_rcnn/roi_data_layer/minibatch.py", line 39, in get_minibatch
    assert len(im_scales) == 1, "Single batch only"
AssertionError: Single batch only
ubuntu@ip-172-31-26-170:~/faster_rcnn_pytorch$

**Comment by abhiML** [comment]
@longcw any help?

**Comment by acgtyrant** [comment]
Check your train.py, is it contains `cfg_from_file('experiments/cfgs/faster_rcnn_end2end.yml')`?

If so, check your yml file, is its `IMS_PER_BATCH` 1?

**Comment by abhiML** [comment]
Hey @acgtyrant could you tell me where the function detect() is being called and what is its use? you will find it in faster_rcnn.py

**Comment by acgtyrant** [comment]
https://github.com/longcw/faster_rcnn_pytorch/blob/master/demo.py#L30

Just as its literally means.

**Comment by abhiML** [comment]
Alright and where are the coordinates of the final pred boxes evaluated during training?

**Comment by acgtyrant** [comment]
Read the source code by yourself.

**Comment by blitu12345** [comment]
The reg layer in RPN has 4k outputs encoding the coordinates of k boxes.(from the paper)
So what actually this layer predicts?Is it predicting the 4 coordinates of boundary boxes directly or predicting the 4 parameterized coordinates of the bounding box.

@acgtyrant  Any help is appreciated.

**Comment by acgtyrant** [comment]
@blitu12345  I think it is 4 parameterized coordinates of the bounding box.

**Comment by brisker** [comment]
@acgtyrant  @longcw  
does this project support batch_size larger than 1?

**Comment by acgtyrant** [comment]
@brisker No.

**Comment by brisker** [comment]
@acgtyrant 
does the original python implementation https://github.com/rbgirshick/py-faster-rcnn support batch_size>1 ? 
if Yes, why does this project do not support?

**Comment by acgtyrant** [comment]
@brisker I think it does. This project is bad.

**Comment by brisker** [comment]
@acgtyrant 
at inference time, the "gt_boxes" is  of course None, but still in FasterRCNN module, the detect function uses the  proposal_target_layer()  and anchor_target_layer() function.  But [here](https://github.com/longcw/faster_rcnn_pytorch/blob/master/faster_rcnn/rpn_msr/proposal_target_layer.py#L112)  does not raise error, given the fact that gt_boxes is None? feeling confused....

**Comment by ParanoidW** [comment]
@abhiML How did you solve the problem in the end? Same error occurs to me now.
