### ISSUE TITLE
cudaCheckError() failed : invalid device function

### ISSUE THREAD

**Issue by iFighting** [longcw/faster_rcnn_pytorch#2]
when i run the demo.py, i met this error:
"load model successfully!
cudaCheckError() failed : invalid device function"

do you know why?
i can use pytorch to train other models, so the installation is correct.
thanks

**Comment by longcw** [comment]
Is there any other error message like the line number for me to find the reason.

**Comment by iFighting** [comment]
你是中国人，我说中文吧，就这两行输出。。我跑其他的模型的时候没有出错的

**Comment by longcw** [comment]
可能是RoIPool 的问题吧，你试试用python实现的RoIPool 能不能跑，在`faster_rcnn/faster_rcnn.py`:
```python
from roi_pooling.modules.roi_pool_py import RoIPool
# from roi_pooling.modules.roi_pool import RoIPool
```

**Comment by iFighting** [comment]
果然是这个原因。。搞好了，不过速度非常慢啊。。一张图片4秒钟

**Comment by longcw** [comment]
是的，python实现的RoIPool需要2,3秒。
但是你那GPU实现的不能跑我也不知道原因了，你试试重新编译，你的GPU型号是什么，我这里GTX1080是没有问题的。
或者强制用CPU版的（只实现了前传），在`faster_rcnn/roi_pooling/functions/roi_pool.py`:
```python
if not features.is_cuda:
    _features = features.permute(0, 2, 3, 1)
    roi_pooling.roi_pooling_forward(self.pooled_height, self.pooled_width, self.spatial_scale,
                                    _features, rois, output)
    # output = output.cuda()
```
改成：
```python
if True:
    is_cuda = features.is_cuda

    _features = features.permute(0, 2, 3, 1)
    if is_cuda:
        _features = _features.cpu()
        rois = rois.cpu()

    roi_pooling.roi_pooling_forward(self.pooled_height, self.pooled_width, self.spatial_scale,
                                    _features, rois, output)
    if is_cuda:
        output = output.cuda()
```

**Comment by iFighting** [comment]
GPU是Tesla K40m，cuda是7.5
用CPU前传。。。速度也很慢啊，囧
我重新编译过了还是这个问题

**Comment by longcw** [comment]
我这里连续跑VOC07的测试集是每帧 0.12s 左右，cpu的RoIPool 只比gpu 慢一点。
see this：https://github.com/smallcorgi/Faster-RCNN_TF/issues/19

> I got the same error (i.e., cudaCheckError() failed : invalid device function) with my Tesla K40. When I changed the -arch parameter in lib/make.sh to sm_35, and rerun make.sh, it worked.

你可以试试按照他说的在`faster_rcnn/make.sh` 里面改 `-arch=sm_35`
不同GPU的计算能力: https://developer.nvidia.com/cuda-gpus

**Comment by longcw** [comment]
我也是刚开始用pytorch，一起交流哈~
我的邮箱longch1024@gmail.com，微信qq啥的可以邮箱发给你。

**Comment by iFighting** [comment]
好的

**Comment by lancejchen** [comment]
对于其它GPU:
```
# Which CUDA capabilities do we want to pre-build for?
# https://developer.nvidia.com/cuda-gpus
#   Compute/shader model   Cards
#   6.1		      P4, P40, Titan X so CUDA_MODEL = 61
#   6.0                    P100 so CUDA_MODEL = 60
#   5.2                    M40
#   3.7                    K80
#   3.5                    K40, K20
#   3.0                    K10, Grid K520 (AWS G2)
#   Other Nvidia shader models should work, but they will require extra startup
#   time as the code is pre-optimized for them.
CUDA_MODELS=30 35 37 52 60 61
```

Credit to https://github.com/mldbai/mldb/blob/master/ext/tensorflow.mk

**Comment by nlqq** [comment]
snow3s@qq.com
