### ISSUE TITLE
python3 compatibility

### ISSUE THREAD

**Issue by meijieru** [longcw/faster_rcnn_pytorch#29]
The faster R-CNN package does not support python3.
Is there any timetable for fix it?

**Comment by adityaarun1** [comment]
I converted this project to python3 using the tool `2to3` and fixing other minor issues.

**Comment by qijiezhao** [comment]
@meijieru Hi,  I met a quite impossible problem of the python version, too.

The provided vggnet model is actually friendly only with python3, I run with error if using python2.
However, when I change the overall python version, I met problem in compiling faster-rcnn repo..

Do you know how to fix this?
