### ISSUE TITLE
run make.sh how we can choose which GPU to use

### ISSUE THREAD

**Issue by liyuanyaun** [longcw/faster_rcnn_pytorch#31]
when i just run make.sh, i can only use gpu 0 which is default, how can i choose which gpu to use? please someone could help me

**Comment by Cadene** [comment]
`CUDA_VISIBLE_DEVICES=0 python train.py` for GPU 0

`CUDA_VISIBLE_DEVICES=1 python train.py` for GPU 1

`CUDA_VISIBLE_DEVICES=2 python train.py` for GPU 2

`CUDA_VISIBLE_DEVICES=n python train.py` for GPU n

**Comment by liyuanyaun** [comment]
thank you very much
