### ISSUE TITLE
How to use just RPN for text detection

### ISSUE THREAD

**Issue by sarthak1996** [longcw/faster_rcnn_pytorch#4]
Hi,
I want to use RPN only and no RCNN to generate region proposals for text regions. Is there a way to do it?

**Comment by longcw** [comment]
Yes, you can use the `RPN` class in `faster_rcnn/faster_rcnn.py` for your tasks.

**Comment by abhiML** [comment]
Hey @sarthak1996 I wanted to know why you chose only rpn for your task?
