### ISSUE TITLE
能不能使用CPU ONLY版本

### ISSUE THREAD

**Issue by JiangWeixian** [longcw/faster_rcnn_pytorch#5]
由于没有CUDA(也没办法装上CUDA)，所以在./make.sh时出错，想问问有没有CPU ONLY的解决办法。希望回复，万分感谢。

**Comment by longcw** [comment]
可以，但是只支持inference，不能训练，没有实现roi pooling cpu版本的backward.
去掉demo 里面的 `.cuda()` 并注释`mask.sh`中的：
```bash
echo "Compiling roi pooling kernels by nvcc..."
nvcc -c -o roi_pooling.cu.o roi_pooling_kernel.cu \
	 -D GOOGLE_CUDA=1 -x cu -Xcompiler -fPIC -arch=sm_52
```
和 `faster_rcnn_pytorch/faster_rcnn/roi_pooling/build.py` 中的：
```python
extra_objects = ['src/cuda/roi_pooling.cu.o']
extra_objects = [os.path.join(this_file, fname) for fname in extra_objects]
```

**Comment by JiangWeixian** [comment]
感谢指导，现在以及出结果了。还有我在说一下还需要修改的地方，还要把`setup.py`里面所有关于cuda注释掉，以及其中ext_modules里面gpu_nms删除。然后你再python demo.py

然而你还要改东西，因为代码里面很计算的地方用到torch`.cuda()`计算。而且传递给函数参数中都默认is_cuda=True，而且还有地方使用gpu_nms，因为比较多，所以就不贴了。所以大家就看着命令行哪里报错，就在对应的文件里面该注释的注释，该改参数的该参数，基本上没有问题了。

感谢作者分享，hhhhhh

**Comment by andrewssobral** [comment]
Hi @longcw 
How can I compile and run training and test with CPU_ONLY mode?
Thanks!

**Comment by sajjad-askari** [comment]
Hi JiangWeixian.
please explain full of details of actions that achieve reply.
please list this actions.

**Comment by chenlx92** [comment]
@JiangWeixian 能否push你修改后的cpu-only的代码？
