### ISSUE TITLE
demo error

### ISSUE THREAD

**Issue by Anears** [longcw/faster_rcnn_pytorch#75]
Hi :D
I followed the [README](https://github.com/longcw/faster_rcnn_pytorch#installation-and-demo) to try to run the demo. There was no problem up to '3' but I got the following error in '4'. What should I do?

> Traceback (most recent call last):
>   File "demo.py", line 4, in <module>
>     from faster_rcnn.faster_rcnn import FasterRCNN
>   File "/home/anears/Desktop/test/faster_rcnn_pytorch/faster_rcnn/faster_rcnn.py", line 10, in <module>
>     from faster_rcnn.fast_rcnn.nms_wrapper import nms
>   File "/home/anears/Desktop/test/faster_rcnn_pytorch/faster_rcnn/fast_rcnn/__init__.py", line 9, in <module>
>     from . import nms_wrapper
>   File "/home/anears/Desktop/test/faster_rcnn_pytorch/faster_rcnn/fast_rcnn/nms_wrapper.py", line 9, in <module>
>     from faster_rcnn.nms.gpu_nms import gpu_nms
> ImportError: /home/anears/Desktop/test/faster_rcnn_pytorch/faster_rcnn/nms/gpu_nms.cpython-36m-x86_64-linux-gnu.so: undefined symbol: __cudaPopCallConfiguration
> 

What is cudaPopCallConfiguration..??
Thank!

**Comment by jaykky01** [comment]
hi:
i have meet this prolem.Did you resolve it?
please tell me the way to resolve the problem.

**Comment by Anears** [comment]
> hi:
> i have meet this prolem.Did you resolve it?
> please tell me the way to resolve the problem.

Hi :D
I tried with another computer and it succeeded.
I think it's a version issue.
I want to tell you the computer environment(eg CUDA version) at that time, but I can not tell because I formatted my computer. sorry.
I hope you solve this problem.
thank.

**Comment by chuong98** [comment]
I have the same problem, and my computer uses AMD threadripper. I am not sure if it is the problem?
